version: '3.8'

services:
  class_one:
    build: .
    volumes:
      - ./videos:/output
    environment:
      - CLASS_URL=
      - USERNAME=
      - PASSWORD=
      - RECORD_DURATION=3060
      - OUTPUT_FILE=

  class_two:
    build: .
    volumes:
      - ./videos:/output
    environment:
      - CLASS_URL=
      - USERNAME=
      - PASSWORD=
      - RECORD_DURATION=3060
      - OUTPUT_FILE=
